RazorTrade:
    mode: si
    acc_id: 1
    module_name: ctp_td
    log_path: /home/op/RazorTrade/log

CounterConfig:
    m_td_addr: tcp://182.254.243.31:30001
    m_md_addr: tcp://182.254.243.31:30011
    # m_td_addr: tcp://182.254.243.31:40001
    # m_md_addr: tcp://182.254.243.31:40011
    m_user: "241512"
    m_passwd: "YuanXiaoYu!123"
    m_brokerid: "9999"
    m_appid: "simnow_client_test"
    m_authcode: "0000000000000000"
    tempFolder: "/home/op/RazorTrade/temp"

