RazorTrade:
    mode: md
    acc_id: 1
    md_mq: md_ctp_xyyuan
    module_name: pnl_watcher
    log_path: /home/xyyuan/RazorTrade/log
    price_mode: Last
    run_mode: Store
    commission_path: /home/xyyuan/RazorTrade/static/commission/commission_config.yaml
    pnl_save_folder: /home/xyyuan/RazorTrade/output/pnl
