Config:
  output_path: /home/xyyuan/RazorTrade/static/timeline
  name_base: timeline
  name_label: current
  note: test
  trading_dates_file_path: /home/data/RiceQuant/trading_dates/TradeDates.csv

Underlyings:
  ag:
    - [2100, 2359]
    - [0, 229]
    - [900, 1014]
    - [1030, 1129]
    - [1330, 1459]
  au:
    - [2100, 2359]
    - [0, 229]
    - [900, 1014]
    - [1030, 1129]
    - [1330, 1459]